---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  labels:
    app: nodejs-ex
  name: nodejs-ex
spec:
  successfulBuildsHistoryLimit: 1
  failedBuildsHistoryLimit: 1
  mountTrustedCA: true
  source:
    type: Git
    git:
      ref: main
      uri: https://github.com/otaviof/nodejs-ex.git
  strategy:
    type: Custom
    customStrategy:
      forcePull: true
      from:
        kind: ImageStreamTag
        name: os-custom-paketo-builder:latest
      env:
        - name: BUILD_PRIVILEGED
          value: "false"
        - name: CNB_PLATFORM_API
          value: "0.10"
  output:
    to:
      kind: ImageStreamTag
      name: nodejs-ex:latest
    pushSecret:
      name: internal-registry